spring:
  application:
    name: security
  datasource:
    url: jdbc:h2:file:./data/mydb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 10